before_install:
  - sudo apt-get -y -qq update
  - sudo apt-get -y -qq install curl make libgc-dev liblua5.1-0-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git -b 99x
  - (cd rock && make -s rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - rock -v sum && ./sum
  - rock -v closure && ./closure
